### ISSUE TITLE
[VISUAL] Recording twice the same speech leads to visual problems 

### ISSUE THREAD

**Issue by ERegalado** [FANMixco/toastmasters-timer#1]
Recording twice the same speech leads to visual problems with the circle as it behaves as if the '30s speech' was selected. Consequently, it marks red after 30s, without marking green and yellow in between. 
To replicate:
1-Select any speech > 30s. E.g.> 5-7min.
2-Record the speech. Press stop to save it.
3-Record a new speech with the same time options. The timer will automatically be defaulted to 30s.

Checking the speeches after recording shows expected values. Therefore, the problem is only related to visuals.

**Comment by ERegalado** [comment]
@FANMixco Verify the solution before closing the issue.

**Comment by FANMixco** [comment]
4- More details are needed from the extreme zoom in your phone, please record a video or gif and upload it. Also, details like the WebWiew and Chrome version (it can be taken from the Play Store).
5- Resize and rotate screen issues, specially in landscape.
